using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;

// for avoir inti error
namespace System.Runtime.CompilerServices
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal class IsExternalInit { }
}

namespace Packt.Shared
{
    public class ImmutablePerson
    {
        public string? FirstName { get; init; }
        public string? LastName { get; init; }
    }

    public record ImmutableVehicle
    {
        public int Wheels { get; init; }
        public string? Color { get; init; }
        public string? Brand { get; init; }
    }

    public record immutableAnimal(string Name, string Species);
    // this line means
    //public record ImmutableAnimal
    //{
    //    public string Name { get; init; }
    //    public string Species { get; init; }

    //    public ImmutableAnimal(string name, string species)
    //    {
    //        Name = name;
    //        Species = species;
    //    }

    //    public void Deconstruct(out string name, out string species)
    //    {
    //        name = Name;
    //        species = Species;
    //    }
    //}
    //this is autogenerated by the line 28

}